pool: Add owner as constructor param
tempus-finance/tempus-protocol pull request #422
Opened 2021-11-04 10:55 UTC by mijovic

2021-11-04 13:25 UTC, axic commented on contracts/TempusPool.sol
> +        address _owner,
Hm, it would be nice to just get this deployed via the controller, but that runs into the factory question.

2021-11-04 13:25 UTC, axic commented on contracts/TempusPool.sol
>          address ctrl,
It would maybe make sense moving controller/owner to be the first items (later).

2021-11-04 13:26 UTC, axic requested changes
Hmm, I think there should be at least one test checking the ownership of a deployed pool. It seems no test was broken by this change.

2021-11-15 21:32 UTC, yuval-weiss commented on test/utils/TempusPool.ts
> +        owner.address,
The deploy functions' `owner` param in the current implementation of TempusPool.ts (before this PR) is actually the deployer of the contract, which is also the owner in the current `master` implementation. This PR separates the contract deployer from the `owner` by making `owner` an actual constructor param - so I think we should separate the `deploy` functions' `owner` param into 2 parameters - `deployer` (which will be used to deploy the contract) and `owner` (which will be passed to the TempusPool constructor).

After we add that I suggest we add a unit test in `TempusPool.Deploy.test` the verifies that deploying a pool with a `deployer` different than the provided `owner` value sets the `TempusPool.owner` property properly.

2021-11-15 21:38 UTC, yuval-weiss commented on contracts/TempusPool.sol
>          require(initInterestRate > 0, "initInterestRate can not be zero");
another possible `require` statement that we can add here is `require(_owner.balance > 0);`. It's not super critical but I think making sure the provided `owner` address is funded with some eth is a nice sanity check that we didn't accidentally have a typo or that we copied the wrong address from testnet or something.

2021-11-17 11:40 UTC, mijovic commented on contracts/TempusPool.sol
> +        address _owner,
I would not start doing factory now, maybe for v2 it would make sense

2021-11-17 13:11 UTC, mijovic commented on contracts/TempusPool.sol
>          require(initInterestRate > 0, "initInterestRate can not be zero");
Added the check

2021-11-17 13:11 UTC, mijovic commented on contracts/TempusPool.sol
>          address ctrl,
Moved them to be the first args

2021-11-24 16:51 UTC, axic commented on contracts/TempusPool.sol
> +        require(_owner.balance > 0, "owner balance can not be zero");
Why?

2021-11-24 16:52 UTC, axic commented on test/utils/TempusPool.ts
> +    deployer:Signer,
Isn't this more clear?
```suggestion
    controller:Signer,
```

2021-11-26 08:51 UTC, closed without merging