Make TempusPool.updateInterestRate public
tempus-finance/tempus-protocol pull request #446
Opened 2021-12-02 15:04 UTC by yuval-weiss

2021-12-03 01:47 UTC, axic commented on contracts/ITempusPool.sol
> +    ///      It should be done first thing before deposit/redeem to avoid arbitrage
Done by whom? Deposit/redeem should already call this.

2021-12-03 09:37 UTC, RedFox20 commented on contracts/ITempusPool.sol
> +    ///      It should be done first thing before deposit/redeem to avoid arbitrage
Yeah this doc is outdated. We should just say this is always done first thing before deposit/redeem

2021-12-03 09:37 UTC, RedFox20 requested changes
Only small fix in docs needed

2022-02-04 13:37 UTC, mijovic commented on contracts/ITempusPool.sol
> +    ///      It should be done first thing before deposit/redeem to avoid arbitrage
I would suggest something like this
```suggestion
    ///      It is done first thing before deposit/redeem to avoid arbitrage
    ///      It is available to call publically to periodically update interest rates in cases of low volume
```

2022-02-07 05:06 UTC, mijovic approved these changes

2022-02-08 08:59 UTC, RedFox20 approved these changes

2022-02-08 09:10 UTC, merged