pool: Consistently use the type uint256 over uint
tempus-finance/tempus-protocol pull request #464
Opened 2021-12-10 10:00 UTC by axic

This ensures we use the types consistently, as currently we have a large mix.

Still, I have avoided touched the mocks, which is also using a mix.

2021-12-10 10:07 UTC, RedFox20 requested changes
Why should we consistently use `uint256`, what's the benefit? It mostly just destroys formatting in specific parts of the code

2021-12-10 10:10 UTC, axic commented
> Why should we consistently use uint256, what's the benefit?

The benefit is consistency and less questions. Either we commit to `uint256` or to `uint`, as otherwise questions arise, such as "so is uint not 256-bits?".

> It mostly just destroys formatting in specific parts of the code

I knew you're going to get put off by those three instances :)

2022-01-28 11:23 UTC, yuval-weiss approved these changes

2022-01-28 11:34 UTC, RedFox20 commented on contracts/TempusPool.sol
> +    function numYieldTokensPerAsset(uint256 backingTokens, uint256 interestRate)
Figure out a way where it doesn't destroy formatting like here and then it'll be ok to merge

2022-01-28 11:56 UTC, merged