Non fungible position manager
tempus-finance/tempus-protocol pull request #554
Opened 2022-03-15 07:55 UTC by yuval-weiss

2022-03-16 08:36 UTC, mijovic commented on contracts/PositionManager.sol
> +            .depositAndLeverage{value: msg.value}(
Maybe this is better format? the one that we have atm looks pretty weird (depositAndLeverage looks like a param)
```suggestion
        (
            uint256 capitalsMinted, 
            uint256 yieldsMinted
        ) = ITempusController(params.tempusPool.controller()).depositAndLeverage{value: msg.value}(
```

2022-03-16 08:38 UTC, mijovic commented
This looks like a good direction to me. What it needs is tests

2022-03-22 10:12 UTC, StefanVitor commented on contracts/PositionManager.sol
> +        uint256 tokenAmount;
I'll write on this way
```suggestion
        uint256 tokenAmount = msg.value;
        if (depositedAsset != address(0)) {
            tokenAmount = IERC20(depositedAsset).untrustedTransferFrom(msg.sender, address(this), params.tokenAmount);
            IERC20(depositedAsset).approve(controller, tokenAmount);
        }
```

2022-03-22 10:12 UTC, StefanVitor commented on contracts/PositionManager.sol
> +    function mintLeveragedPosition(MintParams calldata params) external payable nonReentrant returns (uint256 tokenId) {
NatSpec

2022-03-22 10:12 UTC, StefanVitor commented on contracts/PositionManager.sol
> +    function burnPosition(BurnParams calldata params) external nonReentrant {
NatSpec

2022-03-22 10:18 UTC, StefanVitor commented on contracts/PositionManager.sol
> +    constructor(string memory name, string memory symbol) ERC721(name, symbol) {}
Add Solhint disable
```suggestion
    // solhint-disable-next-line no-empty-blocks
    constructor(string memory name, string memory symbol) ERC721(name, symbol) {}
```

2022-04-05 09:01 UTC, yuval-weiss commented on contracts/PositionManager.sol
> +    function mintLeveragedPosition(MintParams calldata params) external payable nonReentrant returns (uint256 tokenId) {
done

2022-04-05 09:09 UTC, yuval-weiss commented on contracts/PositionManager.sol
> +            .depositAndLeverage{value: msg.value}(
I changed a lot of things, lemme know if you still think it looks weird.

2022-04-05 09:44 UTC, axic commented on contracts/IPositionManager.sol
> +    function positions(uint256 tokenId) external view returns (Position memory);
Perhaps `positionOf` is more in line with other functions?

2022-04-05 09:46 UTC, axic commented on contracts/PositionManager.sol
> +
Ah, marking the variable public generates a getter returning all the fields and not a struct, right?

2022-04-05 09:46 UTC, axic commented on contracts/PositionManager.sol
> +            IERC20(position.tempusPool.yieldBearingToken()).transfer(msg.sender, liquidatedTokenAmount);
These should use safetransfers.

2022-04-05 10:05 UTC, axic commented on contracts/PositionManager.sol
> +        _mint(params.recipient, (tokenId = _nextId++));
Shouldn't this use `_safeMint`?

2022-04-05 10:06 UTC, axic commented on contracts/PositionManager.sol
> +        require(_isApprovedOrOwner(msg.sender, tokenId), "PositionManager: transfer caller is not owner nor approved");
Should use custom error.

2022-04-05 10:07 UTC, axic commented on contracts/PositionManager.sol
> +contract PositionManager is IPositionManager, ERC721, ReentrancyGuard {
Shouldn't this implement `ERC721Enumerable` so the list of positions is easily queryable? (Especially useful for the frontend.)

2022-04-05 10:11 UTC, axic commented on contracts/PositionManager.sol
> +            IERC20(depositedAsset).approve(controller, tokenAmount);
Shouldn't this use `safeIncreaseAllowance`?

2022-04-05 12:02 UTC, yuval-weiss commented on contracts/IPositionManager.sol
> +    function positions(uint256 tokenId) external view returns (Position memory);
I think `positionOf` is a bit confusing, because of the similarity to `balanceOf` I would expect it to accept a `address owner`

2022-04-05 12:45 UTC, yuval-weiss commented on contracts/PositionManager.sol
> +        require(_isApprovedOrOwner(msg.sender, tokenId), "PositionManager: transfer caller is not owner nor approved");
done

2022-04-05 12:45 UTC, yuval-weiss commented on contracts/PositionManager.sol
> +            IERC20(depositedAsset).approve(controller, tokenAmount);
yup, thanks!

2022-04-05 12:46 UTC, yuval-weiss commented on contracts/PositionManager.sol
> +        _mint(params.recipient, (tokenId = _nextId++));
Ja

2022-04-05 12:50 UTC, yuval-weiss commented on contracts/PositionManager.sol
> +
Actually the reason I didn't just use a public mapping is that it's not possible to override an interface-defined getter that returns a struct with a mapping in the implementation.

2022-04-05 12:55 UTC, yuval-weiss commented on contracts/PositionManager.sol
> +
hmmm yeah makes sense

2022-04-05 13:52 UTC, yuval-weiss commented on contracts/IPositionManager.sol
> +        bool toBackingToken;
yeah that's a nice feature. I added it.

2022-04-05 15:41 UTC, axic commented on contracts/IPositionManager.sol
> +        address recipient;
Nit: swap this to match the order of `MintParams`.

2022-04-05 15:42 UTC, axic commented on contracts/PositionManager.sol
> +        IERC20(address(position.tempusPool.principalShare())).safeIncreaseAllowance(
These don't need `safeIncreaseAllowance` as we trust the shares.

2022-04-05 15:43 UTC, axic commented on contracts/PositionManager.sol
> +        _safeMint(params.recipient, (tokenId = _nextId++));
I feel a bit uneasy about nested expressions, would prefer pulling out `tokenId = _nextId++;` to be a statement on its own.

2022-04-05 15:45 UTC, axic commented on contracts/PositionManager.sol
> +    mapping(uint256 => Position) internal _positions;
Nit: `private`.

2022-04-05 18:08 UTC, mijovic commented on contracts/PositionManager.sol
> +        _safeMint(params.recipient, (tokenId = _nextId++));
I agree with this. I feel pretty scary when I see this :)

2022-04-05 18:09 UTC, mijovic commented on contracts/IPositionManager.sol
> +        uint256 leverageMultiplier; /// for fixed positions, use leverageMultiplier=0
I think 1e18 would be 1x leverage which means you have same amount of capitals and yields

2022-04-05 18:10 UTC, mijovic commented on contracts/PositionManager.sol
> +        IERC20(address(position.tempusPool.principalShare())).safeIncreaseAllowance(
+1

2022-04-05 21:04 UTC, mijovic commented on contracts/PositionManager.sol
> +            0,
maybe adding comment for `0`s in this call. What they represent and why they are zeros would be great

2022-04-05 21:22 UTC, axic commented on contracts/IPositionManager.sol
> +        uint256 leverageMultiplier; /// for fixed positions, use leverageMultiplier=0
The leverage code only allows `>1e18`, so not sure if it supposed to allow 1x leverage then.

2022-04-06 08:34 UTC, yuval-weiss commented on contracts/PositionManager.sol
> +            0,
done ser

2022-04-06 10:42 UTC, axic commented on contracts/PositionManager.sol
> +        ITempusPool tempusPool = params.tempusAMM.token0().pool();
Should we add a safety check here for `token0().pool() == token1().pool()` since all these are user submitted fields now?

2022-04-06 10:47 UTC, axic commented on contracts/PositionManager.sol
> +            capitals: SafeCast.toUint128(capitalsMinted),
So this would fit 340282366920938463463.374607431768211455 under 18 decimals. *Should be safe (TM)*

2022-04-06 10:48 UTC, axic commented on contracts/PositionManager.sol
> +    function exitAmmGivenLpAndRedeem(
Hmm, is this code duplication?

2022-04-06 10:49 UTC, yuval-weiss commented on contracts/PositionManager.sol
> +            capitals: SafeCast.toUint128(capitalsMinted),
Yes, should be sifu.

2022-04-06 10:52 UTC, axic commented on contracts/IPositionManager.sol
> +    function positions(uint256 tokenId) external view returns (Position memory);
I'd still prefer something like `position` and not plural.

2022-04-06 11:01 UTC, axic commented on contracts/PositionManager.sol
> +            capitals: SafeCast.toUint128(capitalsMinted),
Well you could just use an immutable for pool/amm and deploy a position manager for each pool :)

2022-04-06 12:18 UTC, yuval-weiss commented on contracts/PositionManager.sol
> +            capitals: SafeCast.toUint128(capitalsMinted),
Yeah but that would complicate the process of fetching all positions for a user... better to leave it as is imo

2022-04-06 12:29 UTC, yuval-weiss commented on contracts/PositionManager.sol
> +    function exitAmmGivenLpAndRedeem(
I separated this block of logic from the main `burn` function because I was getting a `Stack too deep` compile error.

2022-04-06 12:29 UTC, yuval-weiss commented on contracts/PositionManager.sol
> +    function exitAmmGivenLpAndRedeem(
I renamed `exitAmmGivenLpAndRedeem` to `_liquidatePosition` though

2022-04-06 12:34 UTC, yuval-weiss commented on contracts/PositionManager.sol
> +        ITempusPool tempusPool = params.tempusAMM.token0().pool();
The TempusController verifies the provided `tempusAMM` is whitelisted, but I do think it's a good assertion to add to make the PositionManager a bit more resilient and safe from possible future changes such as removing the whitelist from the controller.

2022-04-06 13:30 UTC, StefanVitor commented on contracts/PositionManager.sol
> +            IERC20(tempusPool.backingToken()).safeTransfer(params.recipient, liquidatedTokenAmount);
I would use `transfer` because we trust shares (same on else part).

2022-04-06 13:37 UTC, axic commented on contracts/PositionManager.sol
> +    function exitAmmGivenLpAndRedeem(
Ah ok, why the helper?

2022-04-06 13:51 UTC, StefanVitor approved these changes
From my side, all is good.

2022-04-06 14:10 UTC, axic commented
@yuval-weiss can you squash the commits here please?

2022-04-06 14:14 UTC, axic commented on contracts/IPositionManager.sol
> +        uint256 worstAcceptableCapitalsRate;
Can you describe these fields? It seems this one works differently  depending on leverage.

2022-04-06 14:15 UTC, axic commented on contracts/IPositionManager.sol
> +        uint256 tokenAmount;
Potentially would rename this to `depositedTokenAmount` or `tokenAmountToDeposit`. At least describe it here.

2022-04-07 07:40 UTC, yuval-weiss commented on contracts/PositionManager.sol
> +    function exitAmmGivenLpAndRedeem(
It helped work around the `Stack too deep` error

2022-04-07 08:24 UTC, axic commented on contracts/PositionManager.sol
> +                IERC20(depositedAsset).approve(controller, tokenAmountToDeposit);
Oh this should be `safeIncreaseApproval` as it is an untrusted token.

2022-04-07 10:25 UTC, yuval-weiss commented on contracts/IPositionManager.sol
> +        uint256 worstAcceptableCapitalsRate;
done ser

2022-04-07 10:37 UTC, yuval-weiss commented on contracts/PositionManager.sol
> +        ITempusPool tempusPool = params.tempusAMM.token0().pool();
done

2022-04-07 10:39 UTC, yuval-weiss commented on contracts/PositionManager.sol
> +            capitals: SafeCast.toUint128(capitalsMinted),
closing this

2022-04-07 12:05 UTC, axic requested changes
Missing test cases for:
- mint with token(0), e.g. lido
- burn to backing token

I would also make sure there are all 4 cases done with lido and non-lido to have full coverage of weird token options.

2022-04-07 13:59 UTC, mijovic approved these changes

2022-04-07 17:02 UTC, axic commented on contracts/PositionManager.sol
> +    ) private returns (uint256 liquidatedtokenAmount) {
```suggestion
    ) private returns (uint256 liquidatedTokenAmount) {
```

This?

2022-04-07 17:23 UTC, yuval-weiss commented on contracts/PositionManager.sol
> +    ) private returns (uint256 liquidatedtokenAmount) {
yes :)

2022-04-08 09:20 UTC, axic commented on contracts/IPositionManager.sol
> +interface IPositionManager {
I think this should inherit `IERC721, IERC721Metadata`.

2022-04-08 09:20 UTC, axic commented on contracts/IPositionManager.sol
> +    error InvalidLeverageMultiplier(); /// Provided Leverage Multiplier is invalid
Natspec should be above the line, not next to it.

2022-04-08 09:21 UTC, axic commented on contracts/IPositionManager.sol
> +        ITempusAMM tempusAMM; /// the Tempus AMM (and its Tempus Pool) to use for position creation
Does natspec work here above the struct members? Even if it is ignored there, would prefer there.

2022-04-08 10:11 UTC, yuval-weiss commented on contracts/IPositionManager.sol
> +        ITempusAMM tempusAMM; /// the Tempus AMM (and its Tempus Pool) to use for position creation
done

2022-04-12 12:50 UTC, yuval-weiss commented on contracts/IPositionManager.sol
> +interface IPositionManager {
I agree

2022-04-12 14:20 UTC, mijovic approved these changes
To me, this looks ready to go. Everything is fixed.

2022-04-12 20:06 UTC, axic commented on contracts/PositionManager.sol
> +        IERC20(address(tempusPool.principalShare())).approve(controller, capitals);
I think the `IERC20` wrapping is not needed now, since ammv2 was merged.

2022-04-12 20:13 UTC, RedFox20 commented on contracts/PositionManager.sol
> +        IERC20(address(tempusPool.principalShare())).approve(controller, capitals);
Not yet because IPoolShare doesn't implement IERC20, but this is one of my unfinished PR-s which was waiting for amm/v2 merge.
I'll quickly put it up, so it can be merged to master and this PR can use it...

2022-04-12 20:20 UTC, axic commented on contracts/PositionManager.sol
> +        IERC20(address(tempusPool.principalShare())).approve(controller, capitals);
Ah right due to the conflict of the `OwnerMintable`, I think I did that change locally too, a few times already. Let's hope we can merge it finally.

2022-04-13 08:18 UTC, merged